UPDATE Technologies SET GridX = GridX+1;
UPDATE Technologies SET GridX = GridX-1 WHERE Type IN ('TECH_AGRICULTURE', 'TECH_POTTERY', 'TECH_TRAPPING', 'TECH_ANIMAL_HUSBANDRY', 'TECH_ARCHERY', 'TECH_MINING', 'TECH_CALENDAR', 'TECH_REAL_HORSEBACK_RIDING', 'TECH_MASONRY');

UPDATE Technologies SET Help = 'TXT_KEY_TECH_HELP';